id: A59F88709
title: Toh_504-Account_of_the_Previous_Aspirations_of_Bhaisajyaguruvaiduryaprabha-v2
type: translation
pechas:
- I25F5770C
- ID44F47CA
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-087-009
  eft-text-version: 1.1.6 2021
  title: Toh_504-Account_of_the_Previous_Aspirations_of_Bhaisajyaguruvaiduryaprabha-v2
alignment_to_base:
  I25F5770C/99F1: C0BD
  ID44F47CA/6BDE: C0BD
